# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: trueonot's Development Notes
description: > # this means to ignore newlines until "baseurl:"
  this is a trueonot's development's log powered by jekyll, hosted at github

twitter_username: trueonot
github_username:  trueonot

my:
    displayName: trueonot
    email: trueonot@gmail.com
    realName: Seung Seock, Yang
    realName_kr: 양승석
    jobTitle: "Automotive Software Developer"
    contact:
        qq: .
        email: trueonot@gmail.com
        github: http://www.github.com/trueonot
        qzone: ..
        pinterest: ..
        tel: ..
        address: ..
            .
    skills:
        frontend: ["C, C++", "AUTOSAR", "PERCEPTION", "Image Processing"]
        backend: ["PHP", "JAVA", "PYTHON", "DOCKER"]
        tools: ["Embedded System", "AUTOMOTIVE SOFTWARE", "OPERATING SYSTEM", "OSEK", "FUNCTIONAL SAFETY", ]


# Site settings


# mode: dev
#mode: git
#url: https://trueonot.github.io/
#devurl: http://localhost/

url: https://trueonot.github.io/
baseurl: /

layout: post
email: trueonot@gmail.com
permalink: /:categories/:title

# Build settings
markdown: kramdown
theme: minima
highlighter:  rouge

#gems: [jekyll-paginate]
#paginate: 10
#paginate_path: "page:num"

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
