# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: trueonot's Development Notes
email: trueonot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this is a trueonot's development's log powered by jekyll, hosted at github.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: trueonot
github_username:  trueonot

# Build settings
markdown: kramdown
theme: minima
